//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msrdcui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3389")]
        public string PortNumber {
            get {
                return ((string)(this["PortNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFitSessionToWindowEnabled {
            get {
                return ((bool)(this["DefaultFitSessionToWindowEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultUpdateResolutionOnResizeEnabled {
            get {
                return ((bool)(this["DefaultUpdateResolutionOnResizeEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFullScreenEnabled {
            get {
                return ((bool)(this["DefaultFullScreenEnabled"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem01 {
            get {
                return ((string)(this["RemoteComputerHistoryItem01"]));
            }
            set {
                this["RemoteComputerHistoryItem01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem02 {
            get {
                return ((string)(this["RemoteComputerHistoryItem02"]));
            }
            set {
                this["RemoteComputerHistoryItem02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem03 {
            get {
                return ((string)(this["RemoteComputerHistoryItem03"]));
            }
            set {
                this["RemoteComputerHistoryItem03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem04 {
            get {
                return ((string)(this["RemoteComputerHistoryItem04"]));
            }
            set {
                this["RemoteComputerHistoryItem04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem05 {
            get {
                return ((string)(this["RemoteComputerHistoryItem05"]));
            }
            set {
                this["RemoteComputerHistoryItem05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem06 {
            get {
                return ((string)(this["RemoteComputerHistoryItem06"]));
            }
            set {
                this["RemoteComputerHistoryItem06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem07 {
            get {
                return ((string)(this["RemoteComputerHistoryItem07"]));
            }
            set {
                this["RemoteComputerHistoryItem07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem08 {
            get {
                return ((string)(this["RemoteComputerHistoryItem08"]));
            }
            set {
                this["RemoteComputerHistoryItem08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem09 {
            get {
                return ((string)(this["RemoteComputerHistoryItem09"]));
            }
            set {
                this["RemoteComputerHistoryItem09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteComputerHistoryItem10 {
            get {
                return ((string)(this["RemoteComputerHistoryItem10"]));
            }
            set {
                this["RemoteComputerHistoryItem10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem01 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem01"]));
            }
            set {
                this["RdcWindowTitleHistoryItem01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem02 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem02"]));
            }
            set {
                this["RdcWindowTitleHistoryItem02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem03 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem03"]));
            }
            set {
                this["RdcWindowTitleHistoryItem03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem04 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem04"]));
            }
            set {
                this["RdcWindowTitleHistoryItem04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem05 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem05"]));
            }
            set {
                this["RdcWindowTitleHistoryItem05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem06 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem06"]));
            }
            set {
                this["RdcWindowTitleHistoryItem06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem07 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem07"]));
            }
            set {
                this["RdcWindowTitleHistoryItem07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem08 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem08"]));
            }
            set {
                this["RdcWindowTitleHistoryItem08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem09 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem09"]));
            }
            set {
                this["RdcWindowTitleHistoryItem09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RdcWindowTitleHistoryItem10 {
            get {
                return ((string)(this["RdcWindowTitleHistoryItem10"]));
            }
            set {
                this["RdcWindowTitleHistoryItem10"] = value;
            }
        }
    }
}
